---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - solairen
  - package-ecosystem: nuget
    directory: "/src"
    schedule:
      interval: daily
    assignees:
      - solairen
  - package-ecosystem: nuget
    directory: "/test"
    schedule:
      interval: daily
    assignees:
      - solairen
