---
name: Test on Ubuntu
on:
  push:
    branches-ignore:
      - "main"
  pull_request:
    branches-ignore:
      - "main"

env:
  DISCORD: ${{ secrets.discord_webhook }}
  GH_TOKEN: ${{ secrets.token }}

jobs:
  test:
    name: Test on Ubuntu
    runs-on: ubuntu-latest
    steps:
    - name: Checkout ${{ github.repository }} repository
      uses: actions/checkout@v3
      with:
        repository: ${{ github.repository }}
        ref: ${{ github.ref }}
        token: ${{ env.GH_TOKEN }}
    - name: Run test
      uses: actions/setup-dotnet@v3.0.0
      with:
        dotnet-version: "6.0.x"
    - run: dotnet test test/test.csproj
  notify_on_success:
    name: Send notification on success
    needs:
      - test
    if: ${{ success() }}
    runs-on: ubuntu-latest
    steps:
      - uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ env.DISCORD }}
          description: "Successfully tested on Ubuntu!"
  notify_on_failure:
    name: Send notification on failure
    needs:
      - test
    if: ${{ failure() }}
    runs-on: ubuntu-latest
    steps:
      - uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ env.DISCORD }}
          status: failure
          description: "Test on Ubuntu failed!"
