---
name: Test on Ubuntu
on:
  push:
    branches-ignore:
      - "main"
  pull_request:
    branches-ignore:
      - "main"
jobs:
  test:
    name: Test on Ubuntu
    runs-on: ubuntu-latest
    steps:
    - name: Checkout ${{ github.repository }} repository
      uses: actions/checkout@v2
      with:
        repository: ${{ github.repository }}
        ref: ${{ github.ref }}
        token: ${{ secrets.token }}
    - name: Run test
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: "5.0.x"
    - run: dotnet test test/test.csproj
