---
name: Test on Ubuntu
on:
  push:
    branches-ignore:
      - "main"
  pull_request:
    branches-ignore:
      - "main"

env:
  GH_TOKEN: ${{ secrets.token }}

jobs:
  test:
    name: Test on Ubuntu
    runs-on: ubuntu-latest
    steps:
    - name: Checkout ${{ github.repository }} repository
      uses: actions/checkout@v3
      with:
        repository: ${{ github.repository }}
        ref: ${{ github.ref }}
        token: ${{ env.GH_TOKEN }}
    - name: Run test
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: "6.0.x"
    - run: dotnet test test/test.csproj
