name: Docker registry
on:
  release:
    types:
    - published
jobs:
  push_docker_image_to_dockerhub:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout ${{ github.repository }} repository
      uses: actions/checkout@v2
      with:
        repository: ${{ github.repository }}
        ref: main
        token: ${{ secrets.token }}
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.docker_username }}
        password: ${{ secrets.docker_token }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        file: Docker/Dockerfile
        push: true
        tags: moleszek/salarycalculator:latest
    #- name: Update Docker README
    #  uses: peter-evans/dockerhub-description@v2.1.0
    #  env:
    #    DOCKERHUB_USERNAME: ${{ secrets.dockerhub_username }}
    #    DOCKERHUB_PASSWORD: ${{ secrets.dockerhub_password }}
    #    DOCKERHUB_REPOSITORY: moleszek/salarycalculator
    #    README_FILEPATH: README.md