---
name: Test on Windows
on:
  push:
    branches-ignore:
      - "main"
  pull_request:
    branches-ignore:
      - "main"

env:
  GH_TOKEN: ${{ secrets.token }}
  DISCORD: ${{ secrets.discord_webhook }}

jobs:
  test:
    name: Test on Windows
    runs-on: windows-latest
    steps:
    - name: Checkout ${{ github.repository }} repository
      uses: actions/checkout@v3
      with:
        repository: ${{ github.repository }}
        ref: ${{ github.ref }}
        token: ${{ env.GH_TOKEN }}
    - name: Run test
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'
    - run: dotnet test test/test.csproj
  notify_on_success:
    name: Send notification on success
    needs:
      - test
    if: ${{ success() }}
    runs-on: ubuntu-latest
    steps:
      - uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ env.DISCORD }}
          description: "Successfully tested on Windows!"
  notify_on_failure:
    name: Send notification on failure
    needs:
      - test
    if: ${{ failure() }}
    runs-on: ubuntu-latest
    steps:
      - uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ env.DISCORD }}
          status: failure
          description: "Test on Windows failed!"
